/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Avatar`; params?: Router.UnknownInputParams; } | { pathname: `/components/UITextInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/UIButtons/LinkButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/UIButtons/MainButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/UITexts/H1`; params?: Router.UnknownInputParams; } | { pathname: `/components/UITexts/H2`; params?: Router.UnknownInputParams; } | { pathname: `/components/UITexts/UIText`; params?: Router.UnknownInputParams; } | { pathname: `/pages/LoginPage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Avatar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/UITextInput`; params?: Router.UnknownOutputParams; } | { pathname: `/components/UIButtons/LinkButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/UIButtons/MainButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/UITexts/H1`; params?: Router.UnknownOutputParams; } | { pathname: `/components/UITexts/H2`; params?: Router.UnknownOutputParams; } | { pathname: `/components/UITexts/UIText`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/LoginPage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Avatar${`?${string}` | `#${string}` | ''}` | `/components/UITextInput${`?${string}` | `#${string}` | ''}` | `/components/UIButtons/LinkButton${`?${string}` | `#${string}` | ''}` | `/components/UIButtons/MainButton${`?${string}` | `#${string}` | ''}` | `/components/UITexts/H1${`?${string}` | `#${string}` | ''}` | `/components/UITexts/H2${`?${string}` | `#${string}` | ''}` | `/components/UITexts/UIText${`?${string}` | `#${string}` | ''}` | `/pages/LoginPage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Avatar`; params?: Router.UnknownInputParams; } | { pathname: `/components/UITextInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/UIButtons/LinkButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/UIButtons/MainButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/UITexts/H1`; params?: Router.UnknownInputParams; } | { pathname: `/components/UITexts/H2`; params?: Router.UnknownInputParams; } | { pathname: `/components/UITexts/UIText`; params?: Router.UnknownInputParams; } | { pathname: `/pages/LoginPage`; params?: Router.UnknownInputParams; };
    }
  }
}
